services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=default'
      - 'MYSQL_ROOT_PASSWORD=1qaz2wsx'
      - 'MYSQL_USER=myuser'
      - 'MYSQL_PASSWORD=1qaz2wsx'
    ports:
      - '3306'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
